### ISSUE TITLE
文档路径需要保持一致，国内和国外网站中中文都应该包含 zh-cn，英文都应该包含 en-us

### ISSUE THREAD

**Issue by xiaosongxiaosong** [ossrs/srs-docs#11]
现在路径这块是否能不默认呢？比如，中文是：
http://ossrs.io/zh-cn/docs/doc/git

英文是：
http://ossrs.io/docs/doc/git

能否格式统一成：
http://ossrs.io/en-us/docs/doc/git

因为有可能会贴这个路径，有时候要贴两个，但他们却不一样。

**需要达到的效果是同一个文档的四个路径应该如下：**
- http://ossrs.io/en-us/docs/doc/git
- http://ossrs.io/zh-cn/docs/doc/git
- http://ossrs.net/lts/en-us/docs/doc/git
- http://ossrs.net/lts/zh-cn/docs/doc/git
同时需要注意，页面中的切换语言按钮需要能够跳转到正确的路径上

**Comment by xiaosongxiaosong** [comment]
相关的 issue
- https://github.com/facebook/docusaurus/issues/4723
- https://github.com/facebook/docusaurus/issues/6075
- https://github.com/facebook/docusaurus/issues/3317

**Comment by xiaosongxiaosong** [comment]
参考 https://github.com/facebook/docusaurus/issues/4723#issuecomment-831802183 中的解决方案修改，看起来可以工作，但是会有一下几个问题
- 构建时需要同时使用下面的四条命令进行构建，导致构建命令特别的复杂，后续基本无法维护
- 本地预览也非常麻烦，需要 build 两次后再 serve
- 调试时多语言切换路径中会一直增加 locate 
- [issues 6462](https://github.com/facebook/docusaurus/issues/6462) 
```
"build:io:en-us": "cross-env BASE_URL='/en-us/' docusaurus build --locale en-us --out-dir build/en-us",
"build:io:zh-cn": "cross-env BASE_URL='/zh-cn/' docusaurus build --locale zh-cn --out-dir build/zh-cn",
"build:net:en-us": "cross-env REGION='zh-cn' BASE_URL='/lts/en-us/' docusaurus build --locale en-us --out-dir build/en-us",
"build:net:zh-cn": "cross-env REGION='zh-cn' BASE_URL='/lts/zh-cn/' docusaurus build --locale zh-cn --out-dir build/zh-cn",
```

**Comment by xiaosongxiaosong** [comment]
- 方案二：rewriteSiteConfig 中动态修改 baseUrl 和 outDir
	> 验证不可行
- 方案三： 修改器的 Nginx 配置进行实现
	> 待验证
- 方案四：实现 localeConfigs 增加 baseUrl 支持
	> 推荐方案

**Comment by xiaosongxiaosong** [comment]
## 方案四实现过程记录

### Win 10 运行 docusaurus 项目 start 失败
软连接有关
https://github.com/facebook/docusaurus/pull/6604
https://github.com/facebook/docusaurus/issues/6257

修改 https://github.com/xiaosongxiaosong/docusaurus/blob/089ef14c9acf980447661ce688c77aafb28596fc/website/_dogfooding/dogfooding.config.js#L22 这里可以跑起来
```diff
-       path: fs.realpathSync('_dogfooding/docs-tests-symlink'),
+      path: fs.realpathSync('_dogfooding/_docs tests'),
```

### localizePath 函数逻辑修改

```js
i18n: {
  defaultLocale: 'en',
  locales: [ 'en', 'fr', 'pt-BR', 'ko', 'zh-CN', [length]: 5 ],
  currentLocale: 'en',
  localeConfigs: {
    en: {
      label: 'English',
      direction: 'ltr',
      htmlLang: 'en',
      baseUrl: 'en-us/'
    },
    fr: {
      label: 'Français',
      direction: 'ltr',
      htmlLang: 'fr',
      baseUrl: ''
    },
    'pt-BR': {
      label: 'Português (Brasil)',
      direction: 'ltr',
      htmlLang: 'pt-BR',
      baseUrl: ''
    },
    ko: { label: '한국어', direction: 'ltr', htmlLang: 'ko', baseUrl: '' },
    'zh-CN': {
      label: '中文（中国）',
      direction: 'ltr',
      htmlLang: 'zh-CN',
      baseUrl: ''
    }
  }
}
i18n: {
  defaultLocale: 'en',
  locales: [ 'en', 'fr', 'pt-BR', 'ko', 'zh-CN', [length]: 5 ],
  currentLocale: 'en',
  localeConfigs: {
    en: {
      label: 'English',
      direction: 'ltr',
      htmlLang: 'en',
      baseUrl: 'en-us/'
    },
    fr: {
      label: 'Français',
      direction: 'ltr',
      htmlLang: 'fr',
      baseUrl: ''
    },
    'pt-BR': {
      label: 'Português (Brasil)',
      direction: 'ltr',
      htmlLang: 'pt-BR',
      baseUrl: ''
    },
    ko: { label: '한국어', direction: 'ltr', htmlLang: 'ko', baseUrl: '' },
    'zh-CN': {
      label: '中文（中国）',
      direction: 'ltr',
      htmlLang: 'zh-CN',
      baseUrl: ''
    }
  }
}
```

**Comment by Josh-Cena** [comment]
@xiaosongxiaosong 看到你的 PR 了，我觉得这是可行的，维护者们也讨论过是不是要做这个 feature （https://github.com/facebook/docusaurus/issues/6075），但我不确定的是：

1. 你有考虑过 Nginx 配置重定向的可行性吗？
2. 如果两个 locale 都包含 base URL，那你的网站 root 就是无法访问的,`http://ossrs.io/` 就会是 404。我觉得这样用户体验不好。

**Comment by Josh-Cena** [comment]
好的，你的 PR 我先接手了，后续其他 maintainer 的 review 我会来帮你处理，我也会自己做一些重构，因为它现在有点奇怪。其实我自己也之前研究过这个，但没有完全完成，所以很感谢你能再提起这件事

关于 Nginx 的配置，其实从 `/en-US/` 重定向到 `/` 要比倒过来容易，因为倒过来的话，就需要你在正则表达式里排除掉所有的 locale 名字，但如果从 `/en-US/` 重定向到 `/`，就只用匹配一个 locale 的名字，不需要这么麻烦。你甚至可以用一个 path alias，比如

```
location /en-US {
  alias /var/www/website/
}
```

这样就不需要重写路径了，可以直接访问。当然，具体的可行性我也没试过，我也不是非常了解 Nginx……

**Comment by xiaosongxiaosong** [comment]
方案三试了一下，在 win10 上面配置，baseUrl 是 '/lts/'，如果不增加最后一个 alias 配置，目录跳转和预期是一致的，显示 404，但是加上以后，并不能和预期一样正常显示文件，也不会正确的进行跳转

```
        location = /lts/ {
            return 302 /lts/en-us/;
        }

        location ~ /lts/(docs|blog)(/.*)? {
            return 302 /lts/en-us/$1$2;
        }

        location /lts/en-us/ {
            alias html/lts/;
        }
```

**Comment by xiaosongxiaosong** [comment]
这个功能最新的 2.0.0-beta.22 版本已经支持，等此版本发布后测试验证一下

![image](https://user-images.githubusercontent.com/2703455/176330407-9c455dd6-3b03-4add-90de-d5f106e754eb.png)

https://github.com/facebook/docusaurus/pull/6731
