### ISSUE TITLE
srs.wiki与zh-cn/en-us文档同步

### ISSUE THREAD

**Issue by panda1986** [ossrs/srs-docs#34]
* 如何讲srs.wiki目录下各个版本的md文件分散到srs-docs不同版本的中英文目录下
   * 比如git clone https://github.com/ossrs/srs.wiki.git后，
      * 将v4_EN_Edge.md对应存放到versioned_docs/version-4.0/doc/目录下
      * 将v4_CN_Edge.md对应存放到i18n/zh-cn/docusaurus-plugin-content-docs/version-4.0/doc/目录下
      * 假如以后补充了5.0的wiki, 需要将
        * 将v5_EN_Edge.md对应存放到i18n/en-us/docusaurus-plugin-content-docs/current/doc/目录下
        * 将v5_CN_Edge.md对应存放到i18n/zh-cn/docusaurus-plugin-content-docs/current/doc/目录下
      * srs.wiki需保证每一个文件，对应的中英文文件都存在

* 当srs.wiki更新后，如何将对应文件的修改同步到srs-docs对应的文件
  * 在srs.wiki更新后，可能需要在srs-docs记录之前同步的commit信息，并与srs.wiki进行diff检查
    * 修改文件，则将修改后的文件直接同步到对应目录
    * 增加文件，则需要将文件拷贝到对应目录，并修改sidebar.js, 以及write-translations
    * 删除文件，则需要将对应文件从doc目录中删除，并修改sidebar.js, 以及write-translations

**Comment by winlinvip** [comment]
等我们这次迁移到新的官网后，之前github的wiki，会直接链接到新官网的文档，这样我们就不用同步了。
