### ISSUE TITLE
X509 Certification not valid for www.ossrs.io in Safari

### ISSUE THREAD

**Issue by suzp1984** [ossrs/srs-docs#66]
## Env ##
MacOS Safari and Chrome web browser.

## Bug description ##

open [https://www.ossrs.io/lts/en-us/](https://www.ossrs.io/lts/en-us/) in safari web browser. It will said `This Connection is Not Private`. 
open [https://www.ossrs.io/lts/en-us/](https://www.ossrs.io/lts/en-us/) in chrome web browser. It will redirect to [https://ossrs.io/lts/en-us/](https://ossrs.io/lts/en-us/), and from the `DevTools`, a message print: 

> Redirecting navigation www.ossrs.io -> ossrs.io because the server presented a certificate valid for ossrs.io but not for www.ossrs.io. To disable such redirects launch Chrome with the following flag: --disable-features=SSLCommonNameMismatchHandling

Same issue also exists in `[https://www.ossrs.net/lts/zh-cn/](https://www.ossrs.net/lts/zh-cn/)`, but `ossrs.net` is worse, because I search keyword `srs transcode` in [bing.com](bing.com), the result would list in `www.ossrs.net` instead of `ossrs.net`. 

Because [https://github.com/ossrs/ossrs.net](https://github.com/ossrs/ossrs.net) has not entry to send an issue, so I sent issue here.

## Cause ##

the `ossrs.io` & `ossrs.net` 's x590 certification is not cover the `www.ossrs.io` & `www.ossrs.net` domain, and the server also support the access to `www.ossrs.[io|net]` space. And Safari web browser don't support redirection to the certification validated address.

**Comment by winlinvip** [comment]
Can't replay this issue.

**Comment by winlinvip** [comment]
how to fix this?

**Comment by winlinvip** [comment]
Fixed, request SSL certificate for both ossrs.io and www.ossrs.io by aaPanel.
